http:
  port: 8080


apiEndpoints:
  recommendation:
    host: 'localhost'
    paths: '/api/recommendation*'
  event_tracking:
    host: 'localhost'
    paths: '/api/event_tracking'

  test:
    host: 'localhost'
    paths: '/api/re-test'

  backend:
    host: 'localhost'
    paths: '/api/*'

serviceEndpoints:
  recommender:
    url: 'http://nginx:80'
  backend:
    url: 'http://backend:8001'

policies:
  - proxy
  - request-transformer
  - response-transformer
  - recommendation-pipeline-policy


pipelines:
  recommendation:
    apiEndpoints:
      - recommendation
    policies:
      # - proxy:
      #     - action:
      #         serviceEndpoint: recommender
      #         preserveHost: true
      #         mapResponse: true 

      - recommendation-pipeline-policy:
          - action:
              recommenderService: http://nginx:80/api/recommendation?user_id=
              backendService: http://backend:8001/api/tracks/getTracksById

  event_tracking:
    apiEndpoints:
      - event_tracking
    policies:
      - proxy:
          - action:
              serviceEndpoint: recommender
  test:
    apiEndpoints:
      - test
    policies:
      - proxy:
          - action: 
              serviceEndpoint: recommender

  backend:
    apiEndpoints:
      - backend
    policies:
      - proxy:
          - action:
              serviceEndpoint: backend
              preserveHost: true
