<<<<<<< HEAD
http:
  port: 8080

apiEndpoints:
  # THÊM ENDPOINT MỚI CHO OPTIONS REQUESTS
  cors-options:
    host: '*'
    paths: ['/*']
    methods: ['OPTIONS']
    
  recommendation:
    host: '*'  # ĐỔI TỪ 'localhost' THÀNH '*' ĐỂ CHẤP NHẬN MỌI HOST
    paths: '/api/recommendation*'
  event_tracking:
    host: '*'
    paths: '/api/event_tracking'
  deleteTrack:
    host: '*'
    paths: '/api/tracks/:id'
    methods: ['DELETE']
  createTrack:
    host: '*'
    paths: '/api/tracks/create-track'
  default:
    host: '*'
    paths: '/api/*'
    methods: [GET, POST, PUT, DELETE]
    preserveHeaders: true

serviceEndpoints:
  recommender:
    url: 'http://nginx:80'
  backend:
    url: 'http://backend:8001'

policies:
  - proxy
  - request-transformer
  - response-transformer
  - recommendation-pipeline-policy
  - deleteTrack-pipeline-policy
  - createTrack-pipeline-policy
  - cors

pipelines:
  # PIPELINE MỚI XỬ LÝ OPTIONS REQUESTS
  cors-options:
    apiEndpoints:
      - cors-options
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: ['GET', 'POST', 'PUT', 'DELETE']
              allowedHeaders: ['Content-Type', 'Authorization']
              credentials: true
              maxAge: 86400  # Cache preflight trong 24h

  recommendation:
    apiEndpoints:
      - recommendation
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: ['GET', 'POST', 'PUT', 'DELETE']
              allowedHeaders: ['Content-Type', 'Authorization']
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: recommender
              preserveHeaders: true
      - recommendation-pipeline-policy:
          - action:
              recommenderService: http://nginx:80/api/recommendation?user_id=
              backendService: http://backend:8001/api/tracks/getTracksById

  event_tracking:
    apiEndpoints:
      - event_tracking
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: ['GET', 'POST', 'PUT', 'DELETE']
              allowedHeaders: ['Content-Type', 'Authorization']
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: recommender
              preserveHeaders: true

  deleteTrack:
    apiEndpoints:
      - deleteTrack
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: ['GET', 'POST', 'PUT', 'DELETE']
              allowedHeaders: ['Content-Type', 'Authorization']
              credentials: true
      - deleteTrack-pipeline-policy:
          - action:
              backendService: http://backend:8001/api/tracks
              recommenderService: http://nginx:80/api/delete_track

  createTrack:
    apiEndpoints:
      - createTrack
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: ['GET', 'POST', 'PUT', 'DELETE']
              allowedHeaders: ['Content-Type', 'Authorization']
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: backend
              changeOrigin: true
              stripPath: false
              mapResponse: true
              preserveHeaders: true
      - createTrack-pipeline-policy:
          - action:
              recommenderUrl: http://nginx:80/api/add_track

  default:
    apiEndpoints:
      - default
    policies:
      - cors:
          - action:
              origin: 'http://localhost:5173'
              methods: ['GET', 'POST', 'PUT', 'DELETE']
              allowedHeaders: ['Content-Type', 'Authorization']
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: backend
              changeOrigin: true
              preserveHeaders: true
=======
http:
  port: 8080


apiEndpoints:
  recommendation:
    host: 'localhost'
    paths: '/api/recommendation*'
  event_tracking:
    host: 'localhost'
    paths: '/api/event_tracking'

  deleteTrack:
    host: 'localhost'
    paths: '/api/tracks/:id'

  createTrack:
    host: 'localhost'
    paths: '/api/tracks/create-track'

  backend:
    host: 'localhost'
    paths: '/api/*'

serviceEndpoints:
  recommender:
    url: 'http://nginx:80'
  backend:
    url: 'http://backend:8001'

policies:
  - proxy
  - request-transformer
  - response-transformer
  - recommendation-pipeline-policy
  - deleteTrack-pipeline-policy
  - createTrack-pipeline-policy


pipelines:
  recommendation:
    apiEndpoints:
      - recommendation
    policies:
      # - proxy:
      #     - action:
      #         serviceEndpoint: recommender
      #         preserveHost: true
      #         mapResponse: true 

      - recommendation-pipeline-policy:
          - action:
              recommenderService: http://nginx:80/api/recommendation?user_id=
              backendService: http://backend:8001/api/tracks/getTracksById

  event_tracking:
    apiEndpoints:
      - event_tracking
    policies:
      - proxy:
          - action:
              serviceEndpoint: recommender
              
  deleteTrack:
    apiEndpoints:
      - deleteTrack
    policies:
      - deleteTrack-pipeline-policy:
          - action:
              recommenderService: http://nginx:80/api/delete_track
              backendService: http://backend:8001/api/tracks
  createTrack:
    apiEndpoints:
      - createTrack
    policies:
      - proxy:
          - action:
              serviceEndpoint: backend
              changeOrigin: true
              stripPath: false
              mapResponse: true
      - createTrack-pipeline-policy:
          - action:
              recommenderUrl: http://nginx:80/api/add_track
              

  backend:
    apiEndpoints:
      - backend
    policies:
      - proxy:
          - action:
              serviceEndpoint: backend
              preserveHost: true
>>>>>>> 2b77211b7755c6af3e6a2445fd02be158c15e4a7
